name: salsa-env

channels:
  - conda-forge

#NOTE: gcc compiler is needed to install some packages
dependencies:
    - python>=3.5
    - pip
    - mpi4py
    - matplotlib<=3.2.1
    - numpy==1.16.6
    - scipy
    - yt
    - pandas
    - pip:
        - trident
        - spectacle
        - specutils==0.5.2
        - gwcs==0.10.0
        - astropy
